[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# SPA redirects - handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200