[build]
  command = "npm run build"
  publish = "dist"
  base = "."

[build.environment]
  NODE_VERSION = "18"

# SPA redirects - handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API redirects for serverless functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200